Repository jUqItEr/MetaPilot, pull requests merged in 2023-12, with the labels that each got.

#13 SecurityConfig 수정
  src/main/java/com/dita/metapilot/config/CorsConfig.java
  src/main/java/com/dita/metapilot/config/SecurityConfig.java
  src/main/java/com/dita/metapilot/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dita/metapilot/jwt/JwtAuthorizationFilter.java
  src/main/java/com/dita/metapilot/jwt/JwtProperties.java
  src/main/java/com/dita/metapilot/security/PrincipalDetailService.java
  src/main/java/com/dita/metapilot/user/dto/LoginRequestDto.java
Labels: enhancement

#14 JWT 로그인 기능 완성
  src/main/java/com/dita/metapilot/config/SecurityConfig.java
  src/main/java/com/dita/metapilot/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dita/metapilot/jwt/JwtAuthorizationFilter.java
  src/main/java/com/dita/metapilot/user/controller/UserController.java
Labels: enhancement

#16 Category.xml 추가
  src/main/resources/mappers/category/category.xml
Labels: enhancement

#17 JWT완성 후 디비에 저장
  src/main/java/com/dita/metapilot/config/SecurityConfig.java
  src/main/java/com/dita/metapilot/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dita/metapilot/jwt/JwtAuthorizationFilter.java
  src/main/java/com/dita/metapilot/jwt/JwtProperties.java
  src/main/java/com/dita/metapilot/user/controller/UserController.java
  src/main/java/com/dita/metapilot/user/dto/TokenDto.java
  src/main/java/com/dita/metapilot/user/repository/UserRepository.java
  src/main/java/com/dita/metapilot/user/service/UserService.java
  src/main/resources/mappers/user/user.xml
Labels: enhancement

#18 유저 패키지 코드 정리
  src/main/java/com/dita/metapilot/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dita/metapilot/jwt/JwtAuthorizationFilter.java
  src/main/java/com/dita/metapilot/user/controller/UserController.java
  src/main/java/com/dita/metapilot/user/repository/UserRepository.java
  src/main/java/com/dita/metapilot/user/service/UserService.java
  src/main/resources/mappers/user/user.xml
Labels: enhancement

#19 Category 기능 관리자 권한 이관의 건
  src/main/java/com/dita/metapilot/admin/controller/AdminController.java
  src/main/java/com/dita/metapilot/admin/dto/CategoryDto.java
  src/main/java/com/dita/metapilot/admin/repository/AdminRepository.java
  src/main/java/com/dita/metapilot/admin/service/AdminService.java
  src/main/resources/mappers/admin/admin.xml
Labels: enhancement

#20 소셜 로그인 완성의 건
  src/main/java/com/dita/metapilot/config/CorsConfig.java
  src/main/java/com/dita/metapilot/config/SecurityConfig.java
  src/main/java/com/dita/metapilot/filter/MyFilter1.java
  src/main/java/com/dita/metapilot/filter/MyFilter2.java
  src/main/java/com/dita/metapilot/filter/MyFilter3.java
  src/main/java/com/dita/metapilot/jwt/JwtProperties.java
  src/main/java/com/dita/metapilot/security/OAuth2SuccessHandler.java
  src/main/java/com/dita/metapilot/security/PrincipalDetailService.java
  src/main/java/com/dita/metapilot/security/PrincipalDetails.java
  src/main/java/com/dita/metapilot/security/PrincipalOauth2UserService.java
  src/main/java/com/dita/metapilot/security/provider/GoogleUserInfo.java
  src/main/java/com/dita/metapilot/security/provider/NaverUserInfo.java
  src/main/java/com/dita/metapilot/security/provider/OAuth2UserInfo.java
  src/main/java/com/dita/metapilot/user/controller/SocialController.java
  src/main/java/com/dita/metapilot/user/controller/UserController.java
  src/main/java/com/dita/metapilot/user/dto/RegisterDto.java
  src/main/java/com/dita/metapilot/user/entity/UserEntity.java
  src/main/java/com/dita/metapilot/user/repository/SocialRepository.java
  src/main/java/com/dita/metapilot/user/repository/UserRepository.java
  src/main/java/com/dita/metapilot/user/service/SocialService.java
  src/main/resources/application.yml
  src/main/resources/mappers/user/social.xml
  src/main/resources/mappers/user/user.xml
  src/main/resources/static/pages/account/login.jsx
Labels: enhancement

#21 소셜 로그인 토큰 처리의 건
  src/main/resources/static/pages/account/loginToken.jsx
Labels: enhancement

#22 관리자 페이지 추가
  src/main/resources/static/layout/admin/header.jsx
  src/main/resources/static/layout/admin/sidebar.jsx
  src/main/resources/static/pages/admin/basic/user.jsx
  src/main/resources/static/pages/admin/design/layout.jsx
  src/main/resources/static/pages/admin/menu/category.jsx
  src/main/resources/static/public/image/layoutIcon1.png
  src/main/resources/static/public/image/layoutIcon2.png
  src/main/resources/static/public/image/layoutImg1.png
  src/main/resources/static/public/image/layoutImg2.png
  src/main/resources/static/public/image/viewAlbum.png
  src/main/resources/static/public/image/viewBlog.png
  src/main/resources/static/styles/admin/basic/user.module.css
  src/main/resources/static/styles/admin/design/layout.module.css
  src/main/resources/static/styles/admin/layout/header.module.css
  src/main/resources/static/styles/admin/layout/sidebar.module.css
  src/main/resources/static/styles/admin/menu/category.module.css
Labels: enhancement

#25 admin쪽 카테고리 기능 및 댓글 삭제, 게시글 삭제
  src/main/java/com/dita/metapilot/admin/controller/AdminController.java
  src/main/java/com/dita/metapilot/admin/dto/CategoryUpDownDto.java
  src/main/java/com/dita/metapilot/admin/dto/PostDeletedDto.java
  src/main/java/com/dita/metapilot/admin/dto/PostDto.java
  src/main/java/com/dita/metapilot/admin/entity/CommentEntity.java
  src/main/java/com/dita/metapilot/admin/entity/PostEntity.java
  src/main/java/com/dita/metapilot/admin/repository/AdminRepository.java
  src/main/java/com/dita/metapilot/admin/service/AdminService.java
  src/main/resources/mappers/admin/admin.xml
Labels: enhancement

#26 게시글 페이지 생성
  src/main/resources/static/pages/post/[id]/index.jsx
Labels: enhancement

#28 관리자 페이지 프론트 완료의 건
  src/main/resources/static/layout/admin/sidebar.jsx
  src/main/resources/static/pages/admin/basic/Info.jsx
  src/main/resources/static/pages/admin/statistics/access.jsx
  src/main/resources/static/pages/admin/statistics/views.jsx
  src/main/resources/static/styles/admin/statistics/access.module.css
  src/main/resources/static/styles/admin/statistics/views.module.css
Labels: enhancement

#30 게시글 좋아요, 댓글 목록 버튼 추가의 건
  src/main/resources/static/pages/post/[id]/index.jsx
  src/main/resources/static/styles/post/post.module.css
Labels: enhancement

#31 게시글 header 분리의 건
  src/main/resources/static/components/post/header.jsx
  src/main/resources/static/styles/post/post.module.css
Labels: enhancement

#33 게시글 header 분리, 오류 수정
  src/main/resources/static/components/post/comment.jsx
  src/main/resources/static/components/post/likes.jsx
  src/main/resources/static/pages/post/[id]/index.jsx
Labels: enhancement

#32 PostFile다운로드, 게시물 수정 메서드 수정
  src/main/java/com/dita/metapilot/post/controller/PostController.java
  src/main/java/com/dita/metapilot/post/postFile/controller/PostFileController.java
  src/main/java/com/dita/metapilot/post/postFile/repository/PostFileRepository.java
  src/main/java/com/dita/metapilot/post/postFile/service/PostFileService.java
  src/main/java/com/dita/metapilot/post/repository/PostRepository.java
  src/main/java/com/dita/metapilot/post/service/PostService.java
  src/main/resources/mappers/post/post.xml
  src/main/resources/mappers/post/postFile.xml
Labels: enhancement

#34 게시글 답글, 댓글 기능 추가
  src/main/resources/static/components/post/comment.jsx
  src/main/resources/static/components/post/header.jsx
  src/main/resources/static/components/post/likes.jsx
  src/main/resources/static/pages/post/[postId]/index.jsx
  src/main/resources/static/styles/post/post.module.css
Labels: enhancement

#37 cmsinfodto 수정
  src/main/java/com/dita/metapilot/admin/dto/CmsInfoDto.java
Labels: enhancement

#38 게시글 작성 분리 및 일부분수정
  src/main/java/com/dita/metapilot/post/controller/PostController.java
  src/main/java/com/dita/metapilot/post/dto/FindPostByHashtagDto.java
  src/main/java/com/dita/metapilot/post/dto/HashtagDto.java
  src/main/java/com/dita/metapilot/post/dto/PostDto.java
  src/main/java/com/dita/metapilot/post/dto/PostResponseDto.java
  src/main/java/com/dita/metapilot/post/dto/PostTagDto.java
  src/main/java/com/dita/metapilot/post/entity/PostEntity.java
  src/main/java/com/dita/metapilot/post/postFile/controller/PostFileController.java
  src/main/java/com/dita/metapilot/post/postFile/dto/PostFileDto.java
  src/main/java/com/dita/metapilot/post/postFile/repository/PostFileRepository.java
  src/main/java/com/dita/metapilot/post/postFile/service/PostFileService.java
  src/main/java/com/dita/metapilot/post/repository/PostRepository.java
  src/main/java/com/dita/metapilot/post/service/PostService.java
  src/main/resources/mappers/post/post.xml
  src/main/resources/mappers/post/postFile.xml
Labels: enhancement

#39 파일삭제 쿼리 수정
  src/main/resources/mappers/post/postFile.xml
Labels: bug

#42 인기글 기능 추가
  src/main/java/com/dita/metapilot/post/controller/PostController.java
  src/main/java/com/dita/metapilot/post/dto/PostPopularDto.java
  src/main/java/com/dita/metapilot/post/repository/PostRepository.java
  src/main/java/com/dita/metapilot/post/service/PostService.java
  src/main/resources/mappers/post/post.xml
  src/main/resources/static/components/common/post.jsx
  src/main/resources/static/components/common/trend.jsx
  src/main/resources/static/pages/index.jsx
  src/main/resources/static/pages/post/[postId]/index.jsx
Labels: enhancement

#41 Admin Category기능 추가
  src/main/java/com/dita/metapilot/admin/controller/AdminController.java
  src/main/java/com/dita/metapilot/admin/dto/CategoryDto.java
  src/main/java/com/dita/metapilot/admin/entity/CategoryEntity.java
  src/main/java/com/dita/metapilot/admin/repository/AdminRepository.java
  src/main/java/com/dita/metapilot/admin/service/AdminService.java
  src/main/resources/mappers/admin/admin.xml
  src/main/resources/static/pages/admin/menu/category.jsx
Labels: enhancement

#43 누락된 trend.module.css 추가
  src/main/resources/static/styles/common/trend.module.css
Labels: enhancement

#44 누락된 emptyImage.jpg 추가
  src/main/resources/static/public/image/emptyImage.jpg
Labels: enhancement

#45 Admin - 유저 차단 관련
  src/main/java/com/dita/metapilot/admin/controller/AdminController.java
  src/main/java/com/dita/metapilot/admin/dto/UserDto.java
  src/main/java/com/dita/metapilot/admin/repository/AdminRepository.java
  src/main/java/com/dita/metapilot/admin/service/AdminService.java
  src/main/resources/mappers/admin/admin.xml
Labels: enhancement

#46 댓글 기능 추가
  src/main/java/com/dita/metapilot/comment/controller/CommentController.java
  src/main/java/com/dita/metapilot/comment/dto/CommentDto.java
  src/main/java/com/dita/metapilot/comment/dto/LikeDto.java
  src/main/java/com/dita/metapilot/comment/dto/PostCommentDto.java
  src/main/java/com/dita/metapilot/comment/dto/RefCommentDto.java
  src/main/java/com/dita/metapilot/comment/entity/CommentEntity.java
  src/main/java/com/dita/metapilot/comment/entity/LikeEntity.java
  src/main/java/com/dita/metapilot/comment/file/controller/FileController.java
  src/main/java/com/dita/metapilot/comment/file/controller/FileViewController.java
  src/main/java/com/dita/metapilot/comment/file/dto/FileDto.java
  src/main/java/com/dita/metapilot/comment/file/entity/FileEntity.java
  src/main/java/com/dita/metapilot/comment/file/repository/FileRepository.java
  src/main/java/com/dita/metapilot/comment/file/service/FileService.java
  src/main/java/com/dita/metapilot/comment/repository/CommentRepository.java
  src/main/java/com/dita/metapilot/comment/service/CommentService.java
  src/main/resources/mappers/comment/comment.xml
  src/main/resources/mappers/comment/file.xml
  src/main/resources/mappers/comment/like.xml
Labels: enhancement

#47 쿼리 수정 및 게시글 파일 관련 메서드 추가
  src/main/java/com/dita/metapilot/post/controller/PostController.java
  src/main/java/com/dita/metapilot/post/postFile/controller/PostFileController.java
  src/main/java/com/dita/metapilot/post/postFile/dto/PostFileIdDto.java
  src/main/java/com/dita/metapilot/post/postFile/repository/PostFileRepository.java
  src/main/java/com/dita/metapilot/post/postFile/service/PostFileService.java
  src/main/java/com/dita/metapilot/post/service/PostService.java
  src/main/resources/mappers/post/post.xml
  src/main/resources/mappers/post/postFile.xml
Labels: enhancement

#48 공지, 전체 게시글 목록 추가
  src/main/resources/static/components/common/notice.jsx
  src/main/resources/static/components/common/postList.jsx
  src/main/resources/static/pages/index.jsx
  src/main/resources/static/styles/common/notice.module.css
  src/main/resources/static/styles/common/postList.module.css
  src/main/resources/static/styles/common/trend.module.css
Labels: enhancement

#49 로그인 페이지 수정 및 사용자 인증 로직 추가
  src/main/java/com/dita/metapilot/post/entity/PostEntity.java
  src/main/resources/mappers/post/post.xml
  src/main/resources/static/components/common/notice.jsx
  src/main/resources/static/components/post/likes.jsx
  src/main/resources/static/pages/account/auth.jsx
  src/main/resources/static/pages/account/login.jsx
  src/main/resources/static/pages/account/loginToken.jsx
  src/main/resources/static/pages/index.jsx
  src/main/resources/static/styles/common/trend.module.css
Labels: bug, enhancement

#50 Post View 수정
  src/main/resources/static/components/post/header.jsx
  src/main/resources/static/pages/post/[postId]/index.jsx
  src/main/resources/static/public/image/profile.png
Labels: enhancement

#51 게시글 view 에 내용추가
  src/main/java/com/dita/metapilot/post/entity/PostEntity.java
  src/main/resources/mappers/post/post.xml
Labels: enhancement

#52 Admin Hashtag 수정
  src/main/java/com/dita/metapilot/admin/controller/AdminController.java
  src/main/java/com/dita/metapilot/admin/dto/HashtagDto.java
  src/main/java/com/dita/metapilot/admin/dto/HashtagSearchDto.java
  src/main/java/com/dita/metapilot/admin/entity/HashtagEntity.java
  src/main/java/com/dita/metapilot/admin/repository/AdminRepository.java
  src/main/java/com/dita/metapilot/admin/service/AdminService.java
  src/main/resources/mappers/admin/admin.xml
  src/main/resources/static/pages/admin/menu/tag.jsx
Labels: enhancement

#53 메인페이지 반응형, 게시글목록 추가
  src/main/resources/static/components/common/postList.jsx
  src/main/resources/static/styles/common/notice.module.css
  src/main/resources/static/styles/common/postList.module.css
  src/main/resources/static/styles/common/trend.module.css
  src/main/resources/static/styles/post/post.module.css
Labels: enhancement

#55 메인 페이지 반응형 수정
  src/main/java/com/dita/metapilot/post/dto/PagingDto.java
  src/main/resources/static/components/common/postList.jsx
  src/main/resources/static/styles/common/notice.module.css
  src/main/resources/static/styles/common/postList.module.css
  src/main/resources/static/styles/common/trend.module.css
Labels: enhancement

#56 header.jsx 기능 추가
  src/main/resources/static/components/post/header.jsx
  src/main/resources/static/styles/post/post.module.css
Labels: enhancement

#57 게시글리스트 Paging 처리 구현중
  src/main/java/com/dita/metapilot/post/controller/PostController.java
  src/main/java/com/dita/metapilot/post/dto/PagingDto.java
  src/main/java/com/dita/metapilot/post/repository/PostRepository.java
  src/main/java/com/dita/metapilot/post/service/PostService.java
  src/main/resources/mappers/post/post.xml
  src/main/resources/static/components/common/postList.jsx
Labels: enhancement

#54 adming 페이지 수정의 건
  src/main/java/com/dita/metapilot/admin/controller/AdminController.java
  src/main/java/com/dita/metapilot/admin/repository/AdminRepository.java
  src/main/java/com/dita/metapilot/admin/service/AdminService.java
  src/main/java/com/dita/metapilot/config/SecurityConfig.java
  src/main/resources/mappers/admin/admin.xml
  src/main/resources/static/layout/admin/sidebar.jsx
  src/main/resources/static/pages/admin/basic/Info.jsx
  src/main/resources/static/pages/admin/basic/user.jsx
  src/main/resources/static/pages/admin/design/layout.jsx
  src/main/resources/static/pages/admin/statistics/views.jsx
  src/main/resources/static/styles/admin/basic/info.module.css
  src/main/resources/static/styles/admin/basic/user.module.css
  src/main/resources/static/styles/admin/layout/sidebar.module.css
  src/main/resources/static/styles/admin/statistics/views.module.css
Labels: enhancement

#61 게시글 페이징 기능 추가
  src/main/java/com/dita/metapilot/post/entity/PostEntity.java
  src/main/resources/static/components/common/postList.jsx
  src/main/resources/static/styles/common/postList.module.css
Labels: enhancement

#62 post.xml 게시물리스트 쿼리 수정
  src/main/resources/mappers/post/post.xml
Labels: enhancement

#63 게시글 리스트 검색 기능 추가
  src/main/java/com/dita/metapilot/post/dto/PagingDto.java
  src/main/resources/mappers/post/post.xml
  src/main/resources/static/components/common/postList.jsx
Labels: enhancement

#64 Admin 기능 추가
  src/main/java/com/dita/metapilot/admin/entity/CategoryEntity.java
  src/main/resources/mappers/admin/admin.xml
  src/main/resources/static/pages/admin/menu/category.jsx
  src/main/resources/static/pages/admin/menu/comment.jsx
Labels: enhancement

#65 post쪽 api주소 변경
  src/main/java/com/dita/metapilot/post/controller/PostController.java
  src/main/resources/static/components/common/postList.jsx
  src/main/resources/static/pages/post/[postId]/index.jsx
Labels: enhancement

#66 Admin 수정
  src/main/java/com/dita/metapilot/admin/controller/AdminController.java
  src/main/resources/mappers/admin/admin.xml
  src/main/resources/static/pages/admin/menu/category.jsx
  src/main/resources/static/pages/admin/menu/comment.jsx
  src/main/resources/static/pages/admin/menu/post.jsx
Labels: enhancement

#67 게시글 리스트페이지 페이징 관련 수정
  src/main/java/com/dita/metapilot/post/controller/PostController.java
  src/main/java/com/dita/metapilot/post/dto/PagingDto.java
  src/main/java/com/dita/metapilot/post/repository/PostRepository.java
  src/main/java/com/dita/metapilot/post/service/PostService.java
  src/main/resources/mappers/post/post.xml
  src/main/resources/static/components/common/postList.jsx
Labels: enhancement

#68 댓글 수정, 삭제버튼 추가
  src/main/resources/static/components/common/postList.jsx
  src/main/resources/static/components/post/comment/body.jsx
  src/main/resources/static/styles/common/postList.module.css
  src/main/resources/static/styles/post/post.module.css
Labels: enhancement

#69 comment delete 기능 추가
  src/main/java/com/dita/metapilot/user/entity/UserEntity.java
  src/main/resources/mappers/post/post.xml
  src/main/resources/mappers/user/user.xml
  src/main/resources/static/components/post/comment/body.jsx
  src/main/resources/static/pages/post/[postId]/index.jsx
  src/main/resources/static/styles/post/post.module.css
Labels: enhancement

#70 User role 수정
  src/main/java/com/dita/metapilot/security/PrincipalDetails.java
  src/main/java/com/dita/metapilot/security/PrincipalOauth2UserService.java
  src/main/java/com/dita/metapilot/user/entity/UserEntity.java
  src/main/resources/mappers/user/user.xml
Labels: bug

#74 카테고리 sidebar에 기능 추가
  src/main/java/com/dita/metapilot/category/controller/CategoryController.java
  src/main/java/com/dita/metapilot/category/entity/CategoryCountEntity.java
  src/main/java/com/dita/metapilot/category/repository/CategoryRepository.java
  src/main/java/com/dita/metapilot/category/service/CategoryService.java
  src/main/resources/mappers/category/category.xml
  src/main/resources/static/layout/home/sidebar.jsx
Labels: enhancement

#76 header, post/edit 기능 추가
  src/main/resources/static/layout/home/header.jsx
  src/main/resources/static/pages/index.jsx
  src/main/resources/static/pages/post/edit.jsx
  src/main/resources/static/styles/header.module.css
  src/main/resources/static/styles/post/edit.module.css
  src/main/resources/static/styles/sidebar.module.css
Labels: enhancement

#77 index.module.css 누락 추가
  src/main/resources/static/styles/post/index.module.css
Labels: bug

#78 postList 글관리 삭제 구현
  src/main/java/com/dita/metapilot/post/controller/PostController.java
  src/main/java/com/dita/metapilot/post/repository/PostRepository.java
  src/main/java/com/dita/metapilot/post/service/PostService.java
  src/main/resources/mappers/post/post.xml
  src/main/resources/static/components/common/postList.jsx
Labels: enhancement

#80 edit.jsx 오류수정, SecurityConfig 수정
  src/main/java/com/dita/metapilot/config/SecurityConfig.java
  src/main/resources/static/pages/post/edit.jsx
Labels: bug, enhancement

#81 [id].jsx 추가
  src/main/java/com/dita/metapilot/post/controller/PostController.java
  src/main/java/com/dita/metapilot/post/repository/PostRepository.java
  src/main/java/com/dita/metapilot/post/service/PostService.java
  src/main/resources/mappers/category/category.xml
  src/main/resources/mappers/post/post.xml
  src/main/resources/static/components/common/postList.jsx
  src/main/resources/static/components/common/postListBlogType.jsx
  src/main/resources/static/components/common/postListImageType.jsx
  src/main/resources/static/layout/home/sidebar.jsx
  src/main/resources/static/pages/[id].jsx
  src/main/resources/static/pages/category/[id].jsx
Labels: enhancement

#82 index.jsx
  src/main/resources/static/pages/index.jsx
Labels: enhancement

#84 관리자, index 수정
  src/main/java/com/dita/metapilot/admin/repository/AdminRepository.java
  src/main/java/com/dita/metapilot/admin/service/AdminService.java
  src/main/resources/mappers/admin/admin.xml
  src/main/resources/static/components/common/profile.jsx
  src/main/resources/static/pages/admin/basic/info.jsx
  src/main/resources/static/pages/index.jsx
  src/main/resources/static/styles/index.module.css
  src/main/resources/static/styles/sidebar.module.css
Labels: enhancement

#85 global, sidebar
  src/main/resources/static/layout/home/sidebar.jsx
  src/main/resources/static/styles/globals.css
Labels: bug

#86 sidebar, category, post 기능 추가
  src/main/java/com/dita/metapilot/category/controller/CategoryController.java
  src/main/java/com/dita/metapilot/category/dto/CategoryPostDto.java
  src/main/java/com/dita/metapilot/category/entity/CategoryEntity.java
  src/main/java/com/dita/metapilot/category/repository/CategoryRepository.java
  src/main/java/com/dita/metapilot/category/service/CategoryService.java
  src/main/java/com/dita/metapilot/post/controller/PostController.java
  src/main/java/com/dita/metapilot/post/repository/PostRepository.java
  src/main/java/com/dita/metapilot/post/service/PostService.java
  src/main/resources/mappers/category/category.xml
  src/main/resources/mappers/post/post.xml
  src/main/resources/static/components/common/postList.jsx
  src/main/resources/static/components/common/postListBlogType.jsx
  src/main/resources/static/components/common/postListImageType.jsx
  src/main/resources/static/layout/home/sidebar.jsx
  src/main/resources/static/pages/category/[id].jsx
  src/main/resources/static/pages/index.jsx
Labels: enhancement

#87 postList [비공개] 문구 추가
  src/main/resources/static/components/common/postList.jsx
  src/main/resources/static/components/common/postListBlogType.jsx
  src/main/resources/static/components/common/postListImageType.jsx
Labels: enhancement

#88 로그아웃 새로고침
  src/main/resources/mappers/category/category.xml
  src/main/resources/mappers/post/post.xml
  src/main/resources/static/components/common/postList.jsx
  src/main/resources/static/components/common/postListBlogType.jsx
  src/main/resources/static/pages/account/auth.jsx
Labels: enhancement

#90 draft.js 추가 및 editor수정
  src/main/resources/static/components/common/editor.jsx
  src/main/resources/static/components/post/content.jsx
  src/main/resources/static/components/post/header.jsx
  src/main/resources/static/package.json
  src/main/resources/static/pages/post/edit.jsx
  src/main/resources/static/styles/post/post.module.css
Labels: enhancement

#91 관리자 생성, 회원가입 수정
  src/main/java/com/dita/metapilot/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dita/metapilot/user/controller/UserController.java
  src/main/java/com/dita/metapilot/user/repository/UserRepository.java
  src/main/java/com/dita/metapilot/user/service/UserService.java
  src/main/resources/mappers/user/user.xml
  src/main/resources/static/pages/account/login.jsx
  src/main/resources/static/pages/account/register.jsx
  src/main/resources/static/styles/post/post.module.css
Labels: enhancement
